services:
  - type: web
    name: outdoor-team-app
    env: node
    plan: free
    rootDir: .
    buildCommand: "npm ci && npm run build"
    startCommand: "npm start"
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - fromGroup: outdoor-team-env
    buildEnvVars:
      - key: VITE_SUPABASE_URL
        value: "https://jkgbaaqnfycbjylustan.supabase.co"
      - key: VITE_SUPABASE_ANON_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZ2JhYXFuZnljYmp5bHVzdGFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTg1MDksImV4cCI6MjA3MzY5NDUwOX0.268tOs3eC9VipN85qwCZzDwMwQsaCt_lYzELjc-POAM"

envVarGroups:
  - name: outdoor-team-env
    envVars:
      - key: DATABASE_URL
        value: "" # Add your PostgreSQL connection string from Supabase
      - key: SUPABASE_URL
        value: "" # Add your Supabase project URL
      - key: SUPABASE_ANON_KEY
        value: "" # Add your Supabase anon key
      - key: SUPABASE_SERVICE_ROLE
        value: "" # Add your Supabase service role key
      - key: SUPABASE_JWT_SECRET
        value: "" # Add your Supabase JWT secret
      - key: CORS_ORIGIN
        value: "https://your-frontend-domain.com,capacitor://localhost"
      - key: STRICT_ENV
        value: "true" # Set to false to run in lax mode
      - key: ENABLE_SCHEDULERS
        value: "true" # Set to false to disable cron jobs
      - key: FEATURE_MIGRATIONS
        value: "true" # Run migrations on first deploy
      - key: FEATURE_SEED_DB
        value: "false"
      - key: JWT_SECRET
        generateValue: true # Generate a random secret
      - key: VAPID_PUBLIC_KEY
        value: "" # Add your VAPID public key
      - key: VAPID_PRIVATE_KEY
        value: "" # Add your VAPID private key
      - key: VAPID_EMAIL
        value: "admin@outdoorteam.com"

